services:
  rabbit:
    image: rabbitmq:3.12-management
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
      - "15672"
    restart: "always"